INSERT INTO configuration (type, data) VALUES ('GOOGLE_DRIVE','{
                                                                 \"type\": \"service_account\",
                                                                 \"project_id\": \"dav-ispat\",
                                                                 \"private_key_id\": \"4d7fc94c0dd7e311cf69882fbcb38bbbfe5f3546\",
                                                                 \"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCp/0ak5hg6Qrhw\\nB8nWzrvmzfbsWEpBE4UncEpHjt3uDInZfULtS90K/kQdzwbww0XTbsXDM1YHLXk3\\n4QRamdbeVNaCDZfF9EQ4l2ozPs6Mg0YVWodWCnuTyVuN3fwcVVBG6SjR9QgWbriL\\n2bsiPttN+YHcyJNThHRldg9382IsLR4ociP7y1dudZA8QWUqT6WhLYIckDbsnhBM\\noCRRjgAiguGF1E+Yq8+ea6lQFokfRb0tYoo8/sxiNMZcLPR4OA/oAd+W44Rw0/Se\\ncY9hcn5jIOXffv184E2PSIukULnNO2LhScJngKCJWurBRUWaybckZPPHwU26hfk/\\n4auNqlJfAgMBAAECggEAHPypaB7QDMcpufiqAxXXVoDSVPStHLGeZ94u3ErRLvE2\\nZD6Gtf3UoDZBGTAfB9jURDxEPoe3aJvpaozU+Dn5OIoQ1bZJpfiD1X6EHl7cS3tq\\n7OM15ob9EXMpSGSMw6wMdzr0ufBlQ6X3k+k5jppXPNGJwkL1VC1mx5I9CwAWQl/b\\ns8HWsyeor99GxLdBOS2v+2I990AcD5vHa0THTJJnETLapzxFsnV21YdRAsu0U71Z\\nXcLH2kOr5hwt9L5eoYMmNfTls3hXS7nYv6IjOR7i8JiWCxv/I60CyS7CQi74nDAE\\nwxQPfLM5a1Z6mqUckWn1NongZlCF45ljE7UGVl2QOQKBgQDj3I8p1gmi8NZkFPtq\\nqvczUwvSu6Rvypa9F63ve9JcZph1gTuSv3t+mBUuAMZFieL+VgPfkoqodbGNQ2Mx\\nsN7AwCS2+LkaAnf/MpZk9evYAL2FSsyEbrw52DT3Qn56wYRfvzwmAf9HAbAUWk3A\\nvTujdeHyDWl9xMOkxympCEViMwKBgQC+/W+xNSpsIlsko8GjhxctWYMJiMeZOy+B\\naWbL6C5Togf6Ha7So+xdJLXzdg7VzAGoY38RXNQTkobuwt/nknVsi2u5hvVpTprm\\nVi//k1xn20k5aifThwwglc0aiMhyPfvxxC3aUrRFp9U4Gmn2wNydcNFU4W0iohd8\\nybhaOllbJQKBgC0LwVGn+qe3rOqEK1/fBJek50V1ywA+sKYZNE2P0PprXeB89+X+\\n7M8OCcHabVf59mIJZyKfucGr4rnmhImiSacZVSjG6vD1Y/uTaJ/07fb5zn23V88m\\nhRd6Yp4vCwoBj8XN7HonEuxarRCY+Z4Myul5uH09oYk3iOXeaaH8/Jp5AoGAPAKF\\nxbhey/s/iBOsFCWuMqGderFvhcYC9zaXBhq986lFuGD7PVQkQF/4i7bcknC3VKFu\\nm5X/TOcNXpf8olZybtif0HuHQL9iDF2oVzWGI1vTdibUvLICLXrkJyIzWTIAp8Zs\\nYdz6p6hEZoxmHxIaP53jKDhsgiVMG/mF41PSH8ECgYBDcLUL+220wvQGsuyopQw5\\n1OJGq75TMm0Nl34z84fMv+8a595iHle7ynigDHI2qLb/ZQTk5e3Y50/ka4iRjl9L\\nkDb0GKxbJM/el6Ly3kTianoT57YrG1Hx2LemvwuIsgbCSlNn+ZGDN5dySNXcnsyX\\nBlzKgdJKcF1M2WSgW+0qBA==\\n-----END PRIVATE KEY-----\\n\",
                                                                 \"client_email\": \"drive-service-account@dav-ispat.iam.gserviceaccount.com\",
                                                                 \"client_id\": \"112759031658870304752\",
                                                                 \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",
                                                                 \"token_uri\": \"https://oauth2.googleapis.com/token\",
                                                                 \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",
                                                                 \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/drive-service-account%40dav-ispat.iam.gserviceaccount.com\",
                                                                 \"universe_domain\": \"googleapis.com\"
                                                               }');